# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Backend to use to display websites. qutebrowser supports two different
# web rendering engines / backends, QtWebKit and QtWebEngine. QtWebKit
# was discontinued by the Qt project with Qt 5.6, but picked up as a
# well maintained fork: https://github.com/annulen/webkit/wiki -
# qutebrowser only supports the fork. QtWebEngine is Qt's official
# successor to QtWebKit. It's slightly more resource hungry than
# QtWebKit and has a couple of missing features in qutebrowser, but is
# generally the preferred choice.
# Type: String
# Valid values:
#   - webengine: Use QtWebEngine (based on Chromium).
#   - webkit: Use QtWebKit (based on WebKit, similar to Safari).
c.backend = 'webengine'

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = '"xos4 Terminus", Terminus, Monospace, "DejaVu Sans Mono", Monaco, "Bitstream Vera Sans Mono", "Andale Mono", "Courier New", Courier, "Liberation Mono", monospace, Fixed, Consolas, Terminal'

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '10pt firacode'

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = 'bold 10pt firacode'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '10pt firacode'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '10pt firacode'

# Font used for the hints.
# Type: Font
c.fonts.hints = 'bold 10pt firacode'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '10pt firacode'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '10pt firacode'

# Font used for info messages.
# Type: Font
c.fonts.messages.info = '10pt firacode'

# Font used for warning messages.
# Type: Font
c.fonts.messages.warning = '10pt firacode'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '10pt firacode'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '10pt firacode'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '10pt firacode'

### colors
## Unselected odd tab colors
# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#ebdbb2'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#282828'

## Unselected even tab colors
# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#282828'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = 'darkgrey'

## Selected tab colors
# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = '#282828'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#d79921'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#282828'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#d79921'
