# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

## Bindings for navigating or focusing tabs
config.bind(',1', 'tab-focus 1')
config.bind(',2', 'tab-focus 2')
config.bind(',3', 'tab-focus 3')
config.bind(',4', 'tab-focus 4')
config.bind(',5', 'tab-focus 5')
config.bind(',6', 'tab-focus 6')
config.bind(',7', 'tab-focus 7')
config.bind(',8', 'tab-focus 8')
config.bind(',9', 'tab-focus 9')
config.bind(',0', 'tab-focus -1') # focus on the last available tab

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '10pt firacode'

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = 'bold 10pt firacode'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '10pt firacode'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '10pt firacode'

# Font used for the hints.
# Type: Font
c.fonts.hints = 'bold 10pt firacode'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '10pt firacode'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '10pt firacode'

# Font used for info messages.
# Type: Font
c.fonts.messages.info = '10pt firacode'

# Font used for warning messages.
# Type: Font
c.fonts.messages.warning = '10pt firacode'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '10pt firacode'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '10pt firacode'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '10pt firacode'

### colors
## Unselected odd tab colors
# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#ebdbb2'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#282828'

## Unselected even tab colors
# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#282828'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = 'darkgrey'

## Selected tab colors
# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = '#282828'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#d79921'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#282828'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#d79921'
